### PR TITLE
Fix save and load parties

### PR DESCRIPTION
**Pull request by rtaiello**
Replaced save with save _from_party as well as load;
fix shape mismatch on line 31.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs change / refactoring / dependency upgrade

## Checklist

- [x] The documentation is up-to-date with the changes I made.
- [x] I have read the **CONTRIBUTING** document and completed the CLA (see **CONTRIBUTING**).
- [x] All tests passed, and additional code has been covered with new tests.

### CODE REVIEW

**Comment by rtaiello** [comment]
Hi All, could you let me know why I didn't pass the tests? Thx

**Comment by knottb** [comment]
Thanks, testing failed because our CI has existing failures due to some dependency issues. I can merge these changes and intend to fix the CI shortly.

**Comment by rtaiello** [comment]
> Thanks, testing failed because our CI has existing failures due to some dependency issues. I can merge these changes and intend to fix the CI shortly.
Ok thanks you.
Cheers

**Comment by knottb** [comment]
Closing as this code has been checked in.

**Pull request closed without merging**
